"""test_slug_back

Revision ID: 38c1bba14aff
Revises: 49cbf12343b3
Create Date: 2023-05-26 22:41:18.902996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38c1bba14aff'
down_revision = '49cbf12343b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=50), nullable=True))
        batch_op.create_unique_constraint("slug", ['slug'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Groups', schema=None) as batch_op:
        batch_op.drop_constraint("slug", type_='unique')
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
