"""test_slug

Revision ID: 49cbf12343b3
Revises: 3286ccaeee75
Create Date: 2023-05-26 22:41:04.670018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49cbf12343b3'
down_revision = '3286ccaeee75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Groups', schema=None) as batch_op:
        batch_op.drop_column('slug')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
